# Generated by Django 5.0.6 on 2024-07-21 13:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BoardingPoints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='BusFacility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='DroppingPoints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='NewRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boarding_time', models.TimeField()),
                ('boarding_date', models.DateField()),
                ('dropping_time', models.TimeField()),
                ('dropping_date', models.DateField()),
                ('booked_seats', models.TextField(blank=True, null=True)),
                ('base_price', models.IntegerField()),
                ('price_drop_to', models.IntegerField()),
                ('travel_time', models.TimeField()),
                ('boarding_point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RouteDir.boardingpoints')),
                ('dropping_points', models.ManyToManyField(to='RouteDir.droppingpoints')),
                ('facilites', models.ManyToManyField(to='RouteDir.busfacility')),
            ],
        ),
    ]
