# Generated by Django 5.0.6 on 2024-07-21 16:14

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RouteDir', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newroute',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
