# Generated by Django 5.0.6 on 2024-07-21 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RouteDir', '0002_alter_newroute_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='newroute',
            name='total_seats',
            field=models.IntegerField(default=50),
        ),
    ]
