# Generated by Django 5.0.6 on 2024-07-21 17:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RouteDir', '0003_newroute_total_seats'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newroute',
            name='dropping_points',
        ),
        migrations.CreateModel(
            name='RouteDroppingPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
                ('dropping_point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RouteDir.droppingpoints')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_dropping_points', to='RouteDir.newroute')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('route', 'order')},
            },
        ),
    ]
