# Generated by Django 5.0.6 on 2024-07-21 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RouteDir', '0004_remove_newroute_dropping_points_routedroppingpoint'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newroute',
            name='travel_time',
        ),
    ]
