# Generated by Django 5.0.6 on 2024-07-22 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RouteDir', '0005_remove_newroute_travel_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='newroute',
            name='bus_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
