# Generated by Django 5.0.6 on 2024-07-22 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RouteDir', '0006_newroute_bus_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='newroute',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
