# Generated by Django 5.0.6 on 2024-07-22 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RouteDir', '0007_newroute_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newroute',
            name='id',
            field=models.CharField(editable=False, max_length=4, primary_key=True, serialize=False, unique=True),
        ),
    ]
