# Generated by Django 5.0.6 on 2024-07-22 13:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RouteDir', '0008_alter_newroute_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='routedroppingpoint',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='routedroppingpoint',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='newroute',
            name='route_dropping_points',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='RouteDir.routedroppingpoint'),
        ),
        migrations.RemoveField(
            model_name='routedroppingpoint',
            name='route',
        ),
    ]
