# Generated by Django 5.0.6 on 2024-07-22 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RouteDir', '0009_alter_routedroppingpoint_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newroute',
            name='route_dropping_points',
        ),
        migrations.AddField(
            model_name='newroute',
            name='route_dropping_points',
            field=models.ManyToManyField(to='RouteDir.routedroppingpoint'),
        ),
    ]
