# Generated by Django 5.0.6 on 2024-07-22 13:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RouteDir', '0010_remove_newroute_route_dropping_points_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='routedroppingpoint',
            name='dropping_point',
        ),
        migrations.RemoveField(
            model_name='routedroppingpoint',
            name='order',
        ),
        migrations.AddField(
            model_name='routedroppingpoint',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.RemoveField(
            model_name='newroute',
            name='route_dropping_points',
        ),
        migrations.CreateModel(
            name='RouteDroppingPointCore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
                ('dropping_point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RouteDir.droppingpoints')),
                ('route_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_dropping_point', to='RouteDir.routedroppingpoint')),
            ],
        ),
        migrations.AddField(
            model_name='newroute',
            name='route_dropping_points',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='RouteDir.routedroppingpoint'),
        ),
    ]
