# Generated by Django 5.0.6 on 2024-07-23 04:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RouteDir', '0011_remove_routedroppingpoint_dropping_point_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='routedroppingpointcore',
            options={'ordering': ['order']},
        ),
        migrations.AlterField(
            model_name='newroute',
            name='route_dropping_points',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='route_dropping_points', to='RouteDir.routedroppingpoint'),
        ),
        migrations.AlterUniqueTogether(
            name='routedroppingpointcore',
            unique_together={('route_name', 'order')},
        ),
    ]
