# Generated by Django 5.0.6 on 2024-07-24 13:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RouteDir', '0012_alter_routedroppingpointcore_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentDetails',
            fields=[
                ('id', models.CharField(editable=False, max_length=9, primary_key=True, serialize=False, unique=True)),
                ('customer_name', models.CharField(max_length=100)),
                ('customer_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('customer_phone', models.CharField(max_length=100)),
                ('customer_address', models.CharField(blank=True, max_length=100, null=True)),
                ('payment_id', models.CharField(blank=True, max_length=100, null=True)),
                ('payment_status', models.CharField(blank=True, max_length=100, null=True)),
                ('payment_amount', models.CharField(blank=True, max_length=100, null=True)),
                ('upi_response', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('refunded', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='BookingDetails',
            fields=[
                ('id', models.CharField(editable=False, max_length=9, primary_key=True, serialize=False, unique=True)),
                ('seat_number', models.CharField(blank=True, max_length=100, null=True)),
                ('total_seats', models.IntegerField(default=1)),
                ('total_price', models.IntegerField(default=0)),
                ('base_price', models.IntegerField(default=0)),
                ('booking_date', models.DateField(auto_now_add=True)),
                ('status', models.BooleanField(default=False)),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RouteDir.newroute')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RouteDir.paymentdetails')),
            ],
        ),
    ]
